name: Nexo Build and Test

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/nexo-native/**'
      - 'apps/nexo-web/**'
      - 'packages/**'
      - 'internal/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - '.github/workflows/**'
  # Chỉ chạy push trigger cho workflow files và critical changes
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  # Cho phép chạy manual từ GitHub UI
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual test run'

jobs:
  test-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # Không cancel các job khác khi 1 job fail
      matrix:
        # Chỉ test trên Windows để giảm job count, release workflow sẽ test full
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.14.0'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Debug environment
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Free disk space:"
          df -h || echo "df command not available"

      - name: Install dependencies
        run: |
          echo "Installing dependencies with pnpm..."
          pnpm install --frozen-lockfile --reporter=append-only
        timeout-minutes: 15

      - name: Type check and lint
        run: pnpm run check

      - name: Build internal packages
        run: pnpm run build

      - name: Build Nexo Web application
        run: |
          cd apps/nexo-web
          pnpm run build:native

      - name: Build Nexo Native application
        run: |
          cd apps/nexo-native
          pnpm run build
        env:
          AUTO_OPEN: '0'

      - name: Test build (unpack only)
        run: |
          cd apps/nexo-native
          pnpm run build:unpack

      - name: Upload build artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: nexo-build-${{ matrix.os }}
          path: apps/nexo-native/dist/
          retention-days: 7
