name: Build and Release Nexo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # Không cancel các job khác khi 1 job fail
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.14.0'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check and lint
        run: pnpm run check

      - name: Build internal packages
        run: pnpm run build

      - name: Build Nexo Web application
        run: |
          cd apps/nexo-web
          pnpm run build:native

      - name: Build Nexo Native application
        run: |
          cd apps/nexo-native
          pnpm run build
        env:
          AUTO_OPEN: '0'

      - name: Build and publish (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd apps/nexo-native
          pnpm run publish:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd apps/nexo-native
          pnpm run build:mac
          pnpm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd apps/nexo-native
          pnpm run build:linux
          pnpm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
